- name: Install Docker on frontend servers
  hosts: all # dynamic target via CLI inventory
  become: yes

  vars:
    docker_apt_repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable"

  tasks:
    - name: Install dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      apt_repository:
        repo: "{{ docker_apt_repo }}"
        filename: docker
        state: present
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

- name: Deploy frontend containers
  hosts: frontend # dynamic target via CLI inventory
  become: yes
  tasks:
    - name: Pull frontend images
      shell: |
        docker pull fatemehparmoo/vote:latest
        docker pull fatemehparmoo/result:latest

    - name: Run vote app
      shell: |
        docker rm -f vote || true
        docker run -d \
          --name vote \
          -e REDIS_HOST="{{ redis_endpoint }}" \
          -e REDIS_PORT=6379 \
          -e PGSSLMODE=require \
          -p 8080:80 \
          fatemehparmoo/vote:latest

    - name: Run result app
      shell: |
        docker rm -f result || true
        docker run -d \
          --name result \
          -e PORT=80 \
          -e PG_HOST={{ aurora_endpoint }} \
          -e PG_PORT=5432 \
          -e PG_USER=postgres \
          -e PG_PASSWORD=postgres \
          -e PG_DATABASE=postgres \
          -e PGSSLMODE=require \
          -p 8081:80 \
          fatemehparmoo/result:latest