[bastion]
bastion-ec2 ansible_host=ec2-44-203-214-30.compute-1.amazonaws.com

[frontend]
frontend-ec2-1 ansible_host=10.30.10.47
frontend-ec2-2 ansible_host=10.30.20.66

[backend]
backend-ec2-1 ansible_host=10.30.10.64
backend-ec2-2 ansible_host=10.30.20.197

[private:children]
frontend
backend

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=../../keys/voting-project-key.pem 
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

[private:vars]
ansible_ssh_common_args=-o ProxyJump=ubuntu@ec2-44-203-214-30.compute-1.amazonaws.com -o IdentityFile=../../keys/voting-project-key.pem  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null