[bastion]
bastion-ec2 ansible_host=ec2-100-53-255-185.compute-1.amazonaws.com

[frontend]
frontend-ec2-1 ansible_host=10.30.20.117
frontend-ec2-2 ansible_host=10.30.10.15

[backend]
backend-ec2-1 ansible_host=10.30.20.160
backend-ec2-2 ansible_host=10.30.10.100

[private:children]
frontend
backend

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=../../keys/voting-project-key.pem
ansible_python_interpreter=/usr/bin/python3

[private:vars]
ansible_ssh_common_args='-o ProxyJump=ubuntu@ec2-100-53-255-185.compute-1.amazonaws.com'