[bastion]
bastion-ec2 ansible_host=ec2-44-214-100-67.compute-1.amazonaws.com

[frontend]
frontend-ec2-1 ansible_host=10.30.20.181
frontend-ec2-2 ansible_host=10.30.10.141

[backend]
backend-ec2 ansible_host=10.30.10.213

[db]
db-ec2 ansible_host=10.30.10.94

[private:children]
frontend
backend
db


[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/Users/fatemeh/Desktop/Ironhack/ssh-key/fatemeh-voting-project-key.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

[private:vars]
ansible_ssh_common_args=-o ProxyJump=ubuntu@ec2-44-214-100-67.compute-1.amazonaws.com -o IdentityFile=/Users/fatemeh/Desktop/Ironhack/ssh-key/fatemeh-voting-project-key.pem -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null