apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: worker-container
          resources:
            requests:
              cpu: "250m"
              memory: "384Mi"
            limits:
              cpu: "750m"
              memory: "768Mi"